
language: node_js
node_js:
  - 10
stages:
  - continousIntegration
before_install:
  - chmod +x gradlew
  - sudo apt-get update
addons:
  sonarcloud:
    organization: $SONAR_USER
    token: $SONAR_TOKEN
jobs:
  include:
    - stage: continousIntegration
      script: ./gradlew sonarqube
